---
name: Experimental CI tools
"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  aibolit_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Aibolit
        run: |
          python -m pip install --upgrade pip
          pip install aibolit
      - name: Run Aibolit
        run: |
          aibolit recommend --folder npm-hosted-adapter/src/main/java --format=long --full

  aibolit_2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Aibolit
        run: |
          python -m pip install --upgrade pip
          pip install aibolit
      - name: Run Aibolit
        run: |
          aibolit recommend --folder npm-proxy-adapter/src/main/java --format=long --full
